version: '3.9'
services:
  client:
    container_name: client
    restart: always
    build: ./client
    ports: 
      - "3000:3000"
    links:
      - "app"
  app:
    container_name: backend_app
    restart: always
    build: ./api
    ports: 
     - '4000:4000'
    depends_on:
     - 'mongodb'
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"